runtime: nodejs20
env: flex

service: tachi-submission

manual_scaling:
  instances: 1
  
env_variables:
  NODE_ENV: production

handlers:
  - url: /.*
    script: auto
    secure: always 

network:
  session_affinity: true